services:
  - type: web
    name: Dependify2.0
    env: python
    region: oregon
    plan: free
    branch: master
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python3 server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
